//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyEntry
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ExpensesEntities : DbContext
    {
        public ExpensesEntities()
            : base("name=ExpensesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tdCategory> tdCategory { get; set; }
        public DbSet<tdType> tdType { get; set; }
        public DbSet<tePerson> tePerson { get; set; }
        public DbSet<teTransaction> teTransaction { get; set; }
        public DbSet<vTrans> vTrans { get; set; }
    
        public virtual int spCategoryLines()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCategoryLines");
        }
    
        public virtual int spMoneyEntry(Nullable<decimal> amount, string description, string type, string category, Nullable<System.DateTime> created, Nullable<int> personID)
        {
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            var createdParameter = created.HasValue ?
                new ObjectParameter("Created", created) :
                new ObjectParameter("Created", typeof(System.DateTime));
    
            var personIDParameter = personID.HasValue ?
                new ObjectParameter("PersonID", personID) :
                new ObjectParameter("PersonID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMoneyEntry", amountParameter, descriptionParameter, typeParameter, categoryParameter, createdParameter, personIDParameter);
        }
    
        public virtual int spMoneyUpdate(Nullable<int> transactionID, Nullable<decimal> amount, string transactionDesc, string type, string category, Nullable<System.DateTime> createdDate, Nullable<bool> reconciled, string person)
        {
            var transactionIDParameter = transactionID.HasValue ?
                new ObjectParameter("TransactionID", transactionID) :
                new ObjectParameter("TransactionID", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            var transactionDescParameter = transactionDesc != null ?
                new ObjectParameter("TransactionDesc", transactionDesc) :
                new ObjectParameter("TransactionDesc", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("Type", type) :
                new ObjectParameter("Type", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("Category", category) :
                new ObjectParameter("Category", typeof(string));
    
            var createdDateParameter = createdDate.HasValue ?
                new ObjectParameter("CreatedDate", createdDate) :
                new ObjectParameter("CreatedDate", typeof(System.DateTime));
    
            var reconciledParameter = reconciled.HasValue ?
                new ObjectParameter("Reconciled", reconciled) :
                new ObjectParameter("Reconciled", typeof(bool));
    
            var personParameter = person != null ?
                new ObjectParameter("Person", person) :
                new ObjectParameter("Person", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spMoneyUpdate", transactionIDParameter, amountParameter, transactionDescParameter, typeParameter, categoryParameter, createdDateParameter, reconciledParameter, personParameter);
        }
    
        public virtual int spUpdateTotals()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateTotals");
        }
    }
}
