//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyEntry
{
    using System;
    using System.Collections.Generic;
    
    public partial class tePerson
    {
        public tePerson()
        {
            this.teTransaction = new HashSet<teTransaction>();
        }
    
        public int PersonID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<teTransaction> teTransaction { get; set; }
    }
}
