//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyEntry
{
    using System;
    using System.Collections.Generic;
    
    public partial class teTransaction
    {
        public int TransactionID { get; set; }
        public decimal Amount { get; set; }
        public string TransactionDesc { get; set; }
        public byte TypeID { get; set; }
        public byte CategoryID { get; set; }
        public Nullable<System.DateTime> CreatedDt { get; set; }
        public Nullable<System.DateTime> ModifiedDt { get; set; }
        public Nullable<bool> reconciled { get; set; }
        public Nullable<decimal> RunningTotal { get; set; }
        public Nullable<int> PersonID { get; set; }
    
        public virtual tePerson tePerson { get; set; }
    }
}
