//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyEntry
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTrans
    {
        public int PersonID { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public string TransactionDesc { get; set; }
        public string Type { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int TransactionID { get; set; }
        public Nullable<decimal> RunningTotal { get; set; }
        public Nullable<bool> reconciled { get; set; }
    }
}
